Python (core + DS)

In [4]:
%load_ext sql
%sql postgresql+psycopg2://admin:postgres@localhost:5432/dvdrentaldb

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [16]:
from sqlalchemy import create_engine



engine = create_engine(f"postgresql+psycopg2://admin:postgres@localhost:5432/dvdrentaldb")

In [12]:
import psycopg2
import pandas as pd


conn = psycopg2.connect(
    host="localhost",
    port=5432,
    database="dvdrentaldb",
    user="admin",
    password="postgres",
)
# df = pd.read_sql_query("SELECT * FROM user_events", conn)

In [17]:
import pandas as pd
file_name = "DataCoSupplyChainDataset"
df = pd.read_csv(f"DataCo/{file_name}.csv",  encoding="latin1")
df.to_sql(file_name, engine, if_exists="replace", index=False)

31

In [ ]:
# Language & internals


df["rental_date"] = pd.to_datetime(df["rental_date"])

df["rental_month"] = df["rental_date"].dt.to_period("M")
df = df.groupby(["rental_month", "customer_id"]).size().reset_index(name="count")
df["next_month"] = df["rental_month"] + 1
df2 = pd.merge(
    df[["customer_id", "rental_month", "count"]],
    df[["customer_id", "next_month", "count"]],
    how="outer",
    left_on=["customer_id", "rental_month"],
    right_on=["customer_id", "next_month"],
    suffixes=("_this", "_perv"),
)

In [ ]:
def f(x=[]):
    x.append(1)
    return x
print(f())  # [1]
f() # [1, 1]

# Fix the code
def f(x=None):
    if x is None:
        x = []
    x.append(1)
    return x

[1]

[1, 1]

3.	How does Python’s GIL affect CPU-bound vs I/O-bound code? When would you choose multiprocessing, threading, asyncio?

Python's Global Interpreter Lock (GIL) is a mutex that protects access to Python objects, preventing multiple native threads from executing Python bytecodes at once. This means only one thread can be in a "running" state at any given time, regardless of the number of CPU cores available.</br>
- CPU-bound code is code that spends most of its time performing intensive computations, like numerical calculations or data processing. For this type of code, the GIL is a significant bottleneck. Since only one thread can execute Python bytecode at a time, a multi-threaded Python program won't run any faster on a multi-core machine than a single-threaded one. In fact, it might even be slower due to the overhead of context switching between threads.</br>
- I/O-bound code is code that spends most of its time waiting for external operations to complete, like network requests, disk reads, or database queries. For this type of code, the GIL is less of a concern. When a thread is waiting for an I/O operation, the GIL is released, allowing another thread to acquire it and run. This enables concurrency, as one thread can be doing useful work while another is blocked, waiting for I/O
</br>
- Multiprocessing (ideal choice for CPU-bound) creates new processes, each with its own Python interpreter and memory space. Since each process has its own GIL, they can run on different CPU cores simultaneously, making it the ideal choice for CPU-bound tasks. It allows you to bypass the GIL entirely and achieve true parallelism.</br>
- Threading ( excellent one for I/O-bound) uses multiple threads within a single process, sharing the same memory space and the GIL. This makes it a poor choice for CPU-bound tasks but an excellent one for I/O-bound tasks. Threads are lightweight and efficient for concurrent operations where the program spends most of its time waiting.

4.	Big-O for membership tests in list vs set vs dict. List: O(n), set: O(1) Sets are implemented using a hash table, dict O(1)

5.	How does @property work? When would you use descriptors/dataclasses/__slots__?

In [ ]:
# Pythonic way to provide a cleaner, more readable interface to instance attributes.
class Circle:
    def __init__(self, radius):
        self._radius = radius
    @property
    def radius(self):
        """The radius property getter."""
        return self._radius
    
    @radius.setter
    def radius(self,value):
        """The radius property setter."""
        if value<0:
            raise ValueError("Radius should be positive")
        self._radius=value
c = Circle(6)
print(c.radius) 
c.radius = 4
print(c.radius)

6
4

6. What are context managers? Implement one without @contextmanager

A context manager defines a runtime context for a block of code using the with statement. It ensures that setup and teardown logic always run, even if exceptions occur.

7.	Explain deep copy vs shallow copy; when do you need each?
“A shallow copy only duplicates the outer container, so inner objects are still shared. A deep copy duplicates everything recursively, so you get a fully independent clone. I use shallow copies for flat or intentionally shared structures, and deep copies when I need safe, independent objects.”

In [3]:
import copy

original_list = [[1, 2], [3, 4]]
shallow_copied_list = copy.copy(original_list)
deep_copied_list = copy.deepcopy(original_list)

print(f"Original list: {original_list}")
print(f"Shallow copied list: {shallow_copied_list}")

# Modify a nested object in the shallow copy
shallow_copied_list[0][0] = 99
deep_copied_list[0][1] = 99

print(f"\nAfter modification:")
print(f"Original list: {original_list}")
print(f"Shallow copied list: {shallow_copied_list}")
print(f"Deep copied list: {deep_copied_list}")

# Modifying a top-level element (not a nested object) in the shallow copy
shallow_copied_list.append([5, 6])
original_list.append([7, 8])

print(f"\nAfter appending to shallow copy:")
print(f"Original list: {original_list}")
print(f"Shallow copied list: {shallow_copied_list}")
print(f"Deep copied list: {deep_copied_list}")

Original list: [[1, 2], [3, 4]]
Shallow copied list: [[1, 2], [3, 4]]

After modification:
Original list: [[99, 2], [3, 4]]
Shallow copied list: [[99, 2], [3, 4]]
Deep copied list: [[1, 99], [3, 4]]

After appending to shallow copy:
Original list: [[99, 2], [3, 4], [7, 8]]
Shallow copied list: [[99, 2], [3, 4], [5, 6]]
Deep copied list: [[1, 99], [3, 4]]

8.	How does method resolution order (MRO) work in multiple inheritance?

- Start with the current class.
- Then check its parents (left to right).
- Then check their parents, merging while preserving order.

In [33]:
class A:
    def whoami(self): return "A"

class B(A):
    def whoami(self): return "B"

class C(A):
    def whoami(self): return "C"

class D(B, C):
    pass

print(D.mro())
print(D().whoami())

[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>]
B

9.	What’s the difference between == and is, and where do interns get this wrong?

In [ ]:
a = [1, 2, 3]
b = [1, 2, 3]
x=True
print(a == b)   #✅ True  (same contents)
print(a is b)   # False (different objects, even though contents match)
print(a is a)   # True  (same reference)


# ✅ Identity checks 
a is None
x is True
x is False

# Checking sentinel objects 
if result is NOT_FOUND:

10.	How do you structure a package for a production library (layout, __init__, versioning, pyproject.toml)?

In [ ]:
"""
your-lib/
├─ pyproject.toml
├─ README.md
├─ LICENSE
├─ CHANGELOG.md
├─ .gitignore
├─ .editorconfig
├─ src/
│  └─ your_lib/
│     ├─ __init__.py
│     ├─ _version.py
│     ├─ core.py
│     ├─ utils.py
│     ├─ py.typed              # if you ship type hints
│     └─ data/                 # package data (if any)
├─ tests/
│  ├─ __init__.py
│  └─ test_core.py
├─ docs/                       # optional
└─ scripts/                    # optional CLIs/dev tools
"""

# src/your_lib/__init__.py
from .core import Foo, Bar        # curated imports (public API) 
# Stable public API: only export from __init__. Everything else is private.
from ._version import __version__ # single source of truth (MAJOR.MINOR.PATCH)"0.3.1"

__all__ = ["Foo", "Bar", "__version__"]

11.	Explain type hints in large codebases: Protocol, TypedDict, Union/Literal, pydantic vs stdlib typing.

In [ ]:
from typing import TypeVar, Sequence, Iterable
# Generics / TypeVar
T = TypeVar("T")

def batched(xs: Sequence[T], n: int) -> Iterable[Sequence[T]]:
    # Preserves element types through your APIs (e.g., Sequence[int] -> Iterable[Sequence[int]]).
    for i in range(0, len(xs), n):
        yield xs[i:i+n]

A descriptor is a protocol that allows an object to customize attribute access. It's an object that implements at least one of the __get__, __set__, or __delete__ methods. @property is actually built on top of the descriptor protocol.

You'd use a descriptor when you need to reuse the same access-control logic across multiple classes or attributes. For example, a descriptor could be used to validate an email address for multiple different user classes without rewriting the validation logic each time.

In [29]:
from dataclasses import dataclass

@dataclass
class Point:
    x: float
    y: float

p = Point(1.0, 2.0)
print(p) # Point(x=1.0, y=2.0)

Point(x=1.0, y=2.0)

12.	How do you write unit tests and property-based tests (pytest + hypothesis)?
- Unit Tests: Test: the smallest pieces of code (functions, classes, methods) in isolation to verify correctness of a single unit’s logic.
- regression test: Ensure old bugs don’t come back (“regress”)
- integration test: Test how multiple components work together. Example: Run an ETL → feature pipeline → model prediction end to end, check row counts, schema, and predictions.


13.	Techniques to speed up Python: vectorization, C extensions, Numba, Cython, PyPy—trade-offs.
14.	Memory profiling: tools and strategies (tracemalloc, objgraph). “For memory profiling I usually start with tracemalloc to see where allocations happen, and objgraph to trace why objects aren’t released. For line-by-line usage I add memory_profiler. In DS pipelines I also enforce efficient dtypes, chunked reads, and avoid creating unnecessary copies.”

15.	How would you design an API client module with retries, timeouts, and circuit breakers?

- Transport: use httpx (sync/async) for per-request connect/read timeouts and connection pooling.
- Retries: exponential backoff with jitter; retry only idempotent methods (GET, HEAD, some PUT/DELETE) and retryable status codes (502/503/504, maybe 429 with Retry-After).
- Circuit breaker: track recent failures; transition CLOSED → OPEN after a threshold; after cooldown, go HALF_OPEN and allow a probe; success - closes it, failure re-opens.
- Observability: structured logs, counters (success/failure, open/close events), latency histograms.
- Config: inject via dataclass/env; never hardcode.
- Testability: isolate breaker + retry logic; mock transport; deterministically seed jitter.

In [4]:
import re

text = "Hello, world!"
pattern = r"Hello"

#  attempts to match the pattern only at the beginning of the string.
match_obj = re.match(pattern, text)
if match_obj:
    print(f"re.match found: {match_obj.group()}")
else:
    print("re.match found no match.")

text_2 = "world, Hello!"
match_obj_2 = re.match(pattern, text_2)
if match_obj_2:
    print(f"re.match found: {match_obj_2.group()}")
else:
    print("re.match found no match.")

re.match found: Hello
re.match found no match.

In [ ]:
import re

text = "Hello, world!"
pattern = r"world"

#  the first occurrence where the pattern matches
search_obj = re.search(pattern, text)
if search_obj:
    print(f"re.search found: {search_obj.group()}")
else:
    print("re.search found no match.")

re.search found: world

In [7]:
import re

text = "apple banana apple cherry"
pattern = r"apple"

findall_list = re.findall(pattern, text)
print(f"re.findall found: {findall_list}")

text_4 = "The numbers are 123 and 456."
pattern_4 = r"\d+" # Matches one or more digits
findall_list_4 = re.findall(pattern_4, text_4)
print(f"re.findall found: {findall_list_4}")

re.findall found: ['apple', 'apple']
re.findall found: ['123', '456']

# Algorithms

In [ ]:
d = {'banana': 3, 'apple': 2, 'pear': 1, 'orange': 4}
# sorted(d.items(), key=lambda x: x[1], reverse=False)

sorted(d.items())
sorted(d.items(), key = lambda item:item[1])

[('pear', 1), ('apple', 2), ('banana', 3), ('orange', 4)]

In [ ]:
def append_to_list(val, my_list=[]):
    my_list.append(val)
    return my_list#
print(append_to_list(1))  # [1]
print(append_to_list(2))  # ???
print(append_to_list(2))

[1]
[1, 2]
[1, 2, 2]

In [ ]:
print(append_to_list(2))

[1, 2, 2, 2]

In [ ]:
class Node:
    def __init__(self, data):
        self.data= data
        self.next = None
        self.prev = None

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node
        new_node.prev = last_node

    def prepend(self, data):
        new_node = Node(data)
        if not self.head:
            self.head = new_node
            return
        new_node.next = self.head
        self.head.prev = new_node
        self.head = new_node

    def display(self):
        current_node = self.head
        while current_node:
            print(current_node.data, end=" -> ")
            current_node = current_node.next
    
ls = LinkedList()
ls.append(1)
ls.append(2)
ls.append(3)
ls.prepend(0)
ls.display()
print()

0 -> 1 -> 2 -> 3 ->

In [ ]:
def longest_consecutive(nums):
  nums.sort()
  print(nums)
  i = 0
  j = 0
  largest = 0
  while i<len(nums):
    j=i+1
    while (j<len(nums)) and (nums[j]==nums[j-1]+1):
      j+=1
    largest = max(largest, j-i)
    i=j

  return largest
longest_consecutive( [9,1,4,7,3,-1,0,5,8,-1,6])

[-1, -1, 0, 1, 3, 4, 5, 6, 7, 8, 9]

7

# Numpy

In [ ]:
import numpy as np
a1 = np.array([1, 2, 3])
a2= np.random.random([3,3])
a3 = np.arange(9).reshape(3, 3)
a4  = np.full((3, 3), 5)
a5 = np.array([1.0, 2.0, np.nan, np.nan, 4.0, 5.0])
a6 = np.arange(81).reshape(3,3,3,3)

In [ ]:
a6[0, 1, 1:3]

array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:
print(a5)
# Access only non-missing values
np.ma.masked_invalid(a5).compressed()

[ 1.  2. nan nan  4.  5.]

array([1., 2., 4., 5.])

In [ ]:
a1[::-1]

array([3, 2, 1])

In [ ]:
np.linalg.det(a2)

-0.06602413787050694

In [ ]:
a3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.array([[2.0] * 4] * 3).astype(np.int16)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=int16)

In [ ]:
np.linalg.norm(a3, ord=None, axis=None)

14.2828568570857

In [ ]:
np.equal(a1, a2[0])

array([False, False, False])

In [ ]:
a2[a2 > 0.5]

array([0.82134902, 0.53621257, 0.5320545 ])

In [ ]:
np.vstack((a1,a3))

array([[1, 2, 3],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate((a2,a3), axis=0)

array([[0.82134902, 0.48912678, 0.05118375],
       [0.01471161, 0.53621257, 0.5320545 ],
       [0.28086432, 0.27112886, 0.02807407],
       [0.        , 1.        , 2.        ],
       [3.        , 4.        , 5.        ],
       [6.        , 7.        , 8.        ]])

In [ ]:
a1 , a2, a3, a4

(array([1, 2, 3]),
 array([[0.20543418, 0.68133807, 0.60909172],
        [0.98689223, 0.20137481, 0.69813423],
        [0.7285902 , 0.30681798, 0.13965526]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]))

In [ ]:
a1 @ a2

array([1.6933652 , 2.37493848, 1.19951496])

In [ ]:
a3*a4, a3 @ a4

(array([[ 0,  5, 10],
        [15, 20, 25],
        [30, 35, 40]]),
 array([[ 15,  15,  15],
        [ 60,  60,  60],
        [105, 105, 105]]))

In [ ]:
np.var(a2, axis=1)

array([0.09948003, 0.05995824, 0.01367481])

In [ ]:
a1 * a2

array([[0.09930321, 0.52001792, 1.75707127],
       [0.50201845, 0.28811069, 2.31250698],
       [0.97149153, 1.55533688, 2.21689964]])

In [ ]:
a1+a2

array([[1.01988674, 2.37844886, 3.03941841],
       [1.20009313, 2.0530058 , 3.58142295],
       [1.43106742, 2.13762448, 3.58691143]])

Mismatched axes order; fix with reshape/np.newaxis/np.expand_dims

In [ ]:
import numpy as np
B, T, F = 32, 100, 64            # batch, time, features
X = np.random.randn(B, T, F)      # shape (32, 100, 64)
mu = X.mean(axis=(0,1))           # shape (64,)
sigma = X.std(axis=(0,1))         # shape (64,)
Xz = (X - mu) / sigma             # (32,100,64) op (64,) -> (32,100,64)

In [ ]:
N, H, W, C = 8, 128, 128, 3
imgs = np.random.rand(N, H, W, C)         # (8,128,128,3)
bias = np.array([0.1, -0.2, 0.05])

In [ ]:
time_gain = np.linspace(1, 2, T)

In [ ]:
time_gain[None, None, None, :]

array([[[[1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
          1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]]]])

In [ ]:
N, H, W, C = 8, 128, 128, 3
imgs = np.random.rand(N, H, W, C)         # (8,128,128,3)
bias = np.array([0.1, -0.2, 0.05])        # (3,)
out = imgs + bias                          # works: (8,128,128,3) + (3,)
# Or explicit: bias.reshape(1,1,1,C)

In [ ]:
# Add a time-dependent (T,) vector to a batch of sequences (B,T,F)
B,T,F = 4, 10, 7
X = np.random.randn(B, T, F)         # (4,10,7)
time_gain = np.linspace(1, 2, T)     # (10,)
Y = X * time_gain[:, None]            # ERROR: shapes (4,10,7) and (10,1) misalign
Y = X * time_gain[None, :, None]      # OK: (1,10,1) broadcasts to (4,10,7)

In [ ]:
time_gain[None, :, None]

array([[[1.        ],
        [1.11111111],
        [1.22222222],
        [1.33333333],
        [1.44444444],
        [1.55555556],
        [1.66666667],
        [1.77777778],
        [1.88888889],
        [2.        ]]])

# Pandas

In [ ]:
# user interactions
df = pd.DataFrame({
    'user_id': [1, 1, 2, 2, 3],
    'event': ['click', 'view', 'click', 'click', 'view'],
    'timestamp': pd.to_datetime(['2023-01-01 10:00', '2023-01-01 10:05', '2023-01-02 11:00', '2023-01-02 11:05', '2023-01-03 12:00'])
})
# How would you get the first and last interaction timestamp for each user?
df.groupby('user_id').agg({'timestamp': ['min', 'max']}).reset_index()

  user_id           timestamp
                          min                 max
0       1 2023-01-01 10:00:00 2023-01-01 10:05:00
1       2 2023-01-02 11:00:00 2023-01-02 11:05:00
2       3 2023-01-03 12:00:00 2023-01-03 12:00:00

In [50]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'category': ['A', 'B', 'C', 'A'],
                   'value': [10, 20, 30, 40]})

df

  category  value
0        A     10
1        B     20
2        C     30
3        A     40

In [49]:
# Using a dictionary to map values
category_map = {'A': 'Group 1', 'B': 'Group 2', 'C': 'Group 3'}
df['category_mapped'] = df['category'].map(category_map)

# Using a function
df['value_doubled'] = df['value'].map(lambda x: x * 2)
df

  category  value category_mapped  value_doubled
0        A     10         Group 1             20
1        B     20         Group 2             40
2        C     30         Group 3             60
3        A     40         Group 1             80

In [51]:
df["value"].apply(lambda x : x*2)

0    20
1    40
2    60
3    80
Name: value, dtype: int64

In [ ]:
# It applies a function to every single element (cell) in a DataFrame. It works element-wise.
pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30],
    'C': [100, 200, 300]
}).applymap(lambda x: f'${x:.2f}')

C:\Users\mamma\AppData\Local\Temp\ipykernel_35836\704081592.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  }).applymap(lambda x: f'${x:.2f}')

       A       B        C
0  $1.00  $10.00  $100.00
1  $2.00  $20.00  $200.00
2  $3.00  $30.00  $300.00

In [ ]:
# You need to perform a calculation that involves multiple columns in a row (e.g., axis=1). For example, calculating the sum or range of values across several columns for each row.
# You need to perform an operation on an entire column as a whole (e.g., axis=0), like calculating the max() value of each column.
# The logic you want to apply is more complex than a simple element-wise transformation.
pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30],
    'C': [100, 200, 300]
}).apply(np.sum, axis=0)

A      6
B     60
C    600
dtype: int64

In [ ]:
# Example values
countries = ['US', 'UK']
skus = ['A', 'B']
dates = pd.date_range(start='2024-01-01', periods=10, freq='W-MON')  # Weekly Mondays

# Introduce missing weeks manually
dates_with_gaps = dates.delete([2, 5])  # Remove a couple of weeks

# Build cartesian product
records = []
np.random.seed(42)
for country in countries:
    for sku in skus:
        for date in dates_with_gaps:
            value = np.random.randint(10, 100)
            records.append((country, sku, date, value))

# Create DataFrame
df = pd.DataFrame(records, columns=['country', 'sku', 'date', 'value'])

# Set MultiIndex
df.set_index(['country', 'sku', 'date'], inplace=True)

# Sort for readability
df = df.sort_index()

df.head(2)

                        value
country sku date
UK      A   2024-01-01     39
            2024-01-08     47

In [ ]:
df["week"]=pd.PeriodIndex(df.index.get_level_values(2), freq="W")

In [ ]:
complete_range = pd.date_range(start =df.index.get_level_values(2).min() , end=df.index.get_level_values(2).max(), freq='W-MON')

In [ ]:
complete_range

DatetimeIndex(['2024-01-01', '2024-01-08', '2024-01-15', '2024-01-22',
               '2024-01-29', '2024-02-05', '2024-02-12', '2024-02-19',
               '2024-02-26', '2024-03-04'],
              dtype='datetime64[ns]', freq='W-MON')

In [ ]:
df.index.get_level_values(2).unique()

DatetimeIndex(['2024-01-01', '2024-01-08', '2024-01-22', '2024-01-29',
               '2024-02-12', '2024-02-19', '2024-02-26', '2024-03-04'],
              dtype='datetime64[ns]', name='date', freq=None)

In [ ]:
# Step 1: Reset MultiIndex so we can group by country and sku
df_reset = df.reset_index()

# Step 2: Group by country and sku, and apply asfreq with date as index
filled = (
    df_reset
    .set_index('date')
    .groupby(['country', 'sku'])
    .apply(lambda g: g.sort_index().asfreq('W-MON'))[['value']]
)

# Step 3: Reset index and re-set full MultiIndex if needed
# filled = filled.reset_index().set_index(['country', 'sku', 'date']).sort_index()

filled.head(10)

C:\Users\mamma\AppData\Local\Temp\ipykernel_35836\979442176.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sort_index().asfreq('W-MON'))[['value']]

                        value
country sku date
UK      A   2024-01-01   39.0
            2024-01-08   47.0
            2024-01-15    NaN
            2024-01-22   11.0
            2024-01-29   73.0
            2024-02-05    NaN
            2024-02-12   69.0
            2024-02-19   30.0
            2024-02-26   42.0
            2024-03-04   85.0

In [47]:
pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30],
    'C': [100, 200, 300]
}).apply(lambda x:x-x.mean(axis=0))

     A     B      C
0 -1.0 -10.0 -100.0
1  0.0   0.0    0.0
2  1.0  10.0  100.0

In [ ]:
pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30],
    'C': [100, 200, 300]
}).apply(np.sqrt)

          A         B          C
0  1.000000  3.162278  10.000000
1  1.414214  4.472136  14.142136
2  1.732051  5.477226  17.320508

In [ ]:
pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30],
    'C': [100, 200, 300]
}).style.format('${:.2f}')

In [ ]:
import pandas as pd
prices = pd.DataFrame({
    "time": pd.to_datetime(["2024-09-01 09:00","2024-09-01 09:05","2024-09-01 09:10"]),
    "price": [100, 101, 102]
})
trades = pd.DataFrame({
    "time": pd.to_datetime(["2024-09-01 09:01","2024-09-01 09:06"]),
    "qty": [5, 10]
})
pd.merge_asof(trades, prices, on="time", direction="backward")

                 time  qty  price
0 2024-09-01 09:01:00    5    100
1 2024-09-01 09:06:00   10    101

In [ ]:
df = pd.DataFrame({"id":([1,2],(3,4)), "tags":[["a","b"],["c"]]})
print(df)
df.explode("tags")

       id    tags
0  [1, 2]  [a, b]
1  (3, 4)     [c]

       id tags
0  [1, 2]    a
0  [1, 2]    b
1  (3, 4)    c

In [ ]:
df.explode("tags").explode("id")

  id tags
0  1    a
0  2    a
0  1    b
0  2    b
1  3    c
1  4    c

In [56]:
df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
df.apply(lambda x: [1, 2], axis=1), df.apply(lambda x: [1, 2], axis=1,result_type='expand'), df.apply(lambda x: [1, 2], axis=0)

(0    [1, 2]
 1    [1, 2]
 2    [1, 2]
 dtype: object,
    0  1
 0  1  2
 1  1  2
 2  1  2,
    A  B
 0  1  1
 1  2  2)